# Generated by Django 4.1 on 2022-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_film', models.CharField(max_length=255)),
                ('title_film', models.TextField()),
                ('rating_film', models.TextField()),
                ('release_date', models.TextField()),
                ('review_film', models.TextField()),
            ],
        ),
    ]
